### PR TITLE
Minor Updates / Fixes

### LINKED ISSUE #7: Docs are outdated

### PR DESCRIPTION
**Pull request by CommandString**
Fixed issue with unknown type being thrown when union typing multiple types with null
Made the unknown type error message more verbose
Added the ability to create custom callbacks
~~Added the ability to create custom array callbacks~~

### CODE REVIEW

File: src/Attributes/ArrayCallbackType.php [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+class ArrayCallbackType implements BaseType
+{
+    /**
+     * @param Closure $callback function (mixed $data, mixed $key, MapperInterface $mapper): Array
+     * @param Closure $isTypeCallback function (mixed $data): bool
+     */
+    public function __construct(
+        public readonly string $name,
+        public readonly Closure $callback,
+        public readonly Closure $isTypeCallback,
```
Comment (freezemage0) [inline src/Attributes/ArrayCallbackType.php]: `$validator`?

File: src/Attributes/ArrayCallbackType.php [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+#[Attribute(Attribute::TARGET_PROPERTY)]
+class ArrayCallbackType implements BaseType
+{
+    /**
+     * @param Closure $callback function (mixed $data, mixed $key, MapperInterface $mapper): Array
+     * @param Closure $isTypeCallback function (mixed $data): bool
+     */
+    public function __construct(
+        public readonly string $name,
+        public readonly Closure $callback,
```
Comment (freezemage0) [inline src/Attributes/ArrayCallbackType.php]: Instead of forcing `Closure` I would instead remove the property promotion and change argument type to `callable`, then wrap the passed callable in `Closure::fromCallable()` or use a first-class callable syntax ($callback(...)).

```php
public readonly string $name;
public readonly Closure $callback;
public readonly Closure $validator;
public readonly bool $nullable;

public function __construct(
        string  $name,
        callable $callback,
        callable $validator,
        bool    $nullable = false
) {
    $this->name = $name;
    $this->callback = $callback(...);
    $this->validator = $validator(...);
    $this->nullable = $nullable;
}
```

File: src/Attributes/ArrayCallbackType.php [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+    }
+
+    public function isType(mixed $data): bool
+    {
+        if (!is_array($data)) {
+            return false;
+        }
+
+        foreach ($data as $item) {
+            if (!($this->isTypeCallback)($item)) {
```
Comment (freezemage0) [inline src/Attributes/ArrayCallbackType.php]: I would use strict type check against `false`.

```php
if (($this->isTypeCallback)($item) === false) {
    return false;
}
```

File: src/Attributes/ArrayCallbackType.php [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+
+        return true;
+    }
+
+    public function __invoke(mixed $data, MapperInterface $mapper): array
+    {
+        $array = [];
+
+        foreach ($data as $key => $item) {
+            $array[] = ($this->callback)($item, $key, $mapper);
```
Comment (freezemage0) [inline src/Attributes/ArrayCallbackType.php]: Should this really lose array keys in the result?

File: src/Attributes/CallbackType.php [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+        public readonly Closure $callback,
+        public readonly Closure $isTypeCallback,
+        public readonly bool $nullable = false
+    ) {
+
+    }
+
+    public function isType(mixed $data): bool
+    {
+        return ($this->isTypeCallback)($data);
```
Comment (freezemage0) [inline src/Attributes/CallbackType.php]: Strict type checking?

File: src/Mapper.php [hunk 6]
```diff
@@ -115,6 +118,10 @@ protected function doMapping(): object
                     $data = $type->convert($data);
                 }
 
+                if ($type instanceof CallbackType || $type instanceof ArrayCallbackType) {
```
Comment (freezemage0) [inline src/Mapper.php]: Since both of those implement `__invoke`, you can actually check for `is_callable()` instead of `instanceof` operator.

I would rather extract an interface that defines callable types and check via `instanceof` against that interface. That way you can add more callable types in the future (if you ever wanna do that).

File: src/Attributes/NullType.php [hunk 7]
```diff
@@ -0,0 +1,22 @@
...
+
+#[Attribute(Attribute::TARGET_PROPERTY)]
+class NullType implements BaseType
+{
+    public readonly bool $nullable;
+
+    public function __construct(
+        public readonly string $name
+    ) {
+        $this->nullable = true;
```
Comment (freezemage0) [inline src/Attributes/NullType.php]: This looks really weird. Why not make `isNullable(): bool` in `BaseType` interface?

That way it's required to be present in all implementations, which will be helpful in `Mapper`.

File: tests/AttributeTest.php [hunk 8]
```diff
@@ -19,13 +21,40 @@
 use Tnapf\JsonMapper\Attributes\StringType;
 use Tnapf\JsonMapper\Exception\InvalidArgumentException;
 use Tnapf\JsonMapper\Exception\InvalidValueTypeException;
+use Tnapf\JsonMapper\Mapper;
 use Tnapf\JsonMapper\Tests\Fakes\IssueCategory;
 use Tnapf\JsonMapper\Tests\Fakes\IssueState;
 use Tnapf\JsonMapper\Tests\Fakes\RolePermission;
 use Tnapf\JsonMapper\Tests\Fakes\AttributeDuplication;
 
 class AttributeTest extends TestCase
```
Comment (freezemage0) [inline tests/AttributeTest.php:33]: Tests for `NullType`?

File: tests/AttributeTest.php [hunk 9]
```diff
@@ -19,13 +21,40 @@
...
+    {
+        $callbackType = new CallbackType(
+            name: 'callbackType',
+            callback: static fn (string $value) => $value . '5',
+            isTypeCallback: static fn (mixed $value) => ($value === 'test')
+        );
+
+        $this->assertTrue($callbackType->isType('test'));
+        $this->assertFalse($callbackType->isType('test2'));
+        $this->assertSame('test5', $callbackType('test', new Mapper()));
```
Comment (freezemage0) [inline tests/AttributeTest.php]: In case of unit tests, every program component should be isolated.

I think you should stub `MapperInterface` here.

**Review by freezemage0 — CHANGES_REQUESTED** [review]

File: src/Attributes/ArrayCallbackType.php (hunk 1 above)
Comment (CommandString) [reply src/Attributes/ArrayCallbackType.php]: Named it is type to match the is type method but I can use validator

File: src/Attributes/ArrayCallbackType.php (hunk 4 above)
Comment (CommandString) [reply src/Attributes/ArrayCallbackType.php]: Woops overlooked that. Thanks for noticing

File: tests/AttributeTest.php (hunk 9 above)
Comment (CommandString) [reply tests/AttributeTest.php]: Not familiar with stubs. I'll look into it though

File: src/Attributes/ArrayCallbackType.php (hunk 1 above)
Comment (freezemage0) [reply src/Attributes/ArrayCallbackType.php]: I suggest making it `$validatorCallback` then.

**Comment by CommandString** [comment]
I decided to take a different approach to this. I decided to make CallbackType and abstract class that you extend that way the type can be reusable. Additionally, I added `isNullable` as a method to BaseType (as the commit messages show) and then added more tests.

File: src/Attributes/CallbackType.php [hunk 10]
```diff
@@ -0,0 +1,22 @@
+<?php
+
+namespace Tnapf\JsonMapper\Attributes;
+
+use Tnapf\JsonMapper\MapperInterface;
+
+abstract class CallbackType implements BaseType
```
Comment (freezemage0) [inline src/Attributes/CallbackType.php]: This is no longer a `CallbackType` since there's no callback. This looks more like `TypeTemplate` to me.

Is this really needed? `map` method can be a part of something like `MappableTypeInterface` that extends the `BaseType` interface.

File: tests/AttributeTest.php [hunk 11]
```diff
@@ -19,13 +21,43 @@
...
+    {
+        $callbackType = new class ('test', true) extends CallbackType {
+            public function isType(mixed $data): bool
+            {
+                return is_int($data);
+            }
+
+            public function map(mixed $data, MapperInterface $mapper): mixed
+            {
+                return $data + 1;
```
Comment (freezemage0) [inline tests/AttributeTest.php]: Looks like a misuse of a type. This method implements a specific logic that's beyond the scope of "converting" data.

File: src/Attributes/NullType.php [hunk 12]
```diff
@@ -0,0 +1,24 @@
...
+
+namespace Tnapf\JsonMapper\Attributes;
+
+use Attribute;
+
+#[Attribute(Attribute::TARGET_PROPERTY)]
+class NullType implements BaseType
+{
+    public function __construct(
+        public readonly string $name
```
Comment (freezemage0) [inline src/Attributes/NullType.php]: Inline the argument?

**Review by freezemage0 — COMMENTED** [review]
Mostly lgtm. I guess you can merge it now if you like it how it is.

File: src/Attributes/NullType.php (hunk 12 above)
Comment (CommandString) [reply src/Attributes/NullType.php]: Not sure what you mean

File: src/Attributes/CallbackType.php (hunk 10 above)
Comment (CommandString) [reply src/Attributes/CallbackType.php]: Definitely needed for something I'm working on currently

File: tests/AttributeTest.php (hunk 11 above)
Comment (CommandString) [reply tests/AttributeTest.php]: Not sure I understand

File: src/Attributes/NullType.php (hunk 12 above)
Comment (freezemage0) [reply src/Attributes/NullType.php]:
```php
public function __construct(public readonly string $name)
```

File: src/Attributes/CallbackType.php (hunk 10 above)
Comment (freezemage0) [reply src/Attributes/CallbackType.php]: > Definitely needed for something I'm working on currently

I mean, this class can be safely replaced with an interface, because it's used as an interface.

File: tests/AttributeTest.php (hunk 11 above)
Comment (freezemage0) [reply tests/AttributeTest.php]: > Not sure I understand

Well, `+ 1` usually is not something that transforms one type of data into another (it only does as a side effect).

Mapping string to integer or array to object doesn't actually change the data itself (excluding the cases of string `'asdf'` to int `0`).

I understand that it doesn't really matter for that specific test, but I prefer seeing tests use features as intended. I consider modifying the input data to be an unexpected behavior of a mapper.

File: src/Attributes/CallbackType.php (hunk 10 above)
Comment (CommandString) [reply src/Attributes/CallbackType.php]: I see, main reason I'm using an abstract class is to make sure these properties are public readonly

File: tests/AttributeTest.php (hunk 11 above)
Comment (CommandString) [reply tests/AttributeTest.php]: No I see, it makes sense. I can update the test to make it more accurate

File: src/Attributes/NullType.php (hunk 12 above)
Comment (CommandString) [reply src/Attributes/NullType.php]: Shocking phpcsf didn't change that

File: src/Attributes/CallbackType.php (hunk 10 above)
Comment (freezemage0) [reply src/Attributes/CallbackType.php]: > I see, main reason I'm using an abstract class is to make sure these properties are public readonly

I see. It's just that not every implementation will require these properties, as you do in your projects that use this package. I would suggest a compromise of `MappableType` interface (extending the `BaseType` interface) and this class implementing that interface then. This is really optional, so if you don't feel like it then I see nothing wrong leaving it as it is.

Comment (CommandString) [reply src/Attributes/CallbackType.php]: I would do this if it wasn't for the `isNullable` method. Which would have to be repeated in every CallbackType implementation. However, I think renaming `CallbackType` to `MappableType` probably a good decision as the name might be misleading

**Review by freezemage0 — APPROVED** [review]
lgtm
